export enum GET_TEST_API_DATA_TYPES {
  GET_TEST_API_DATA_REQUEST = "GET_TEST_API_DATA_REQUEST",
  GET_TEST_API_DATA_SUCCESS = "GET_TEST_API_DATA_SUCCESS",
  GET_TEST_API_DATA_FAILED = "GET_TEST_API_DATA_FAILED",
};
