export enum GET_INCOME_DATA_TYPES {
  GET_INCOME_DATA_REQUEST = "GET_INCOME_DATA_REQUEST",
  GET_INCOME_DATA_SUCCESS = "GET_INCOME_DATA_SUCCESS",
  GET_INCOME_DATA_FAILED = "GET_INCOME_DATA_FAILED",
};
