export enum GET_EXPENSES_DATA_TYPES {
  GET_EXPENSES_DATA_REQUEST = "GET_EXPENSES_DATA_REQUEST",
  GET_EXPENSES_DATA_SUCCESS = "GET_EXPENSES_DATA_SUCCESS",
  GET_EXPENSES_DATA_FAILED = "GET_EXPENSES_DATA_FAILED",
};
